create_pdf_extraction_task:
  description: >
    Extract the complete text content from the PDF file. {pdf_url}
    Make sure to preserve the document structure as much as possible, including paragraphs, lists, and section headings. Pay special attention to maintaining the hierarchical organization of the content.
  expected_output:
    The complete text content of the PDF document with preserved structure.
    The output should contain all text from the document, organized in a way that maintains the original document flow and organization.
  agent: create_pdf_agent
  output_file: output/pdf_text.json

create_section_extraction_task:
  description: >
    Use the extracted output from the previous task present at {pdf_text_url}.
    And then identify and extract the following specific sections: {sections_to_extract}.
    For each section:
    1. Identify the section boundaries accurately
    2. Extract the complete content of each section
    3. Maintain the original formatting within each section
    4. Ensure no content from other sections is included
    The sections may be indicated by headings like "2. Problem" or simply "Problem".
  expected_output:
    '''A structured object containing the extracted sections with the following format:
    {{
    "{sections_to_extract[0]}": "[complete content of section]",
    "{sections_to_extract[1]}": "[complete content of section]",
    "{sections_to_extract[2]}": "[complete content of section]"
    }}
    Each section should contain its complete content with proper formatting preserved'''
  agent: create_section_extraction_agent
  output_file: output/extacted_text.json

create_section_json_to_steps_task:
  description: >
    Use the extracted output from the previous task present at {extracted_text_url} to convert the solution description into a structured JSON for diagram generation.  
    The JSON should follow this structure: {jsonOutput} and ensure all fields are filled in the given JSON.  

    **Key Instructions:**  
    - Identify all components, their relationships, external systems, and workflow steps from the provided solution text.  
    - Each component should have a unique ID, appropriate categorization (such as frontend, backend, database, external service, queue, workflow, etc.), and an appropriate icon name.  
    - Accurately map relationships between components as described in the solution text.  
    - Define workflow steps based on the described implementation process.  
    - Set clear and complete metadata for the diagram.  

    **Icon Assignment Rules:**  
    - If a specific technology is mentioned (such as AWS Lambda, Azure Function, PostgreSQL, Redis, etc.), use the exact technology icon from the known set.  
    - If no technology is defined, do NOT default to AWS or Azure icons.  
    - Instead, intelligently assign the most appropriate general Eraser.io icon (refer to eraser_icons.csv) based on the functional type of the component. For example:  
      - Databases ➡ use `database`  
      - Backend services ➡ use `server`  
      - Frontend applications ➡ use `html5`  
      - APIs ➡ use `api`  
      - Any unclassified system ➡ use `box`  
    - Do not use placeholder icon names like `"General-eraser.icon"`.  

    **Ensure:**  
    - No mixing of technologies in the JSON.  
    - All components and workflow steps are clearly defined and follow the architecture flow.

  expected_output: >
    A well-structured JSON object representing the architectural solution, containing all necessary information to generate a clean, accurate, and understandable diagram.

  agent: section_json_to_steps_agent
  output_file: output/diagram.json

rule_validation_task:
  description: >
    Perform a rule-based validation check on the given system architecture to ensure that:
    Reference for the incompatible teck can be found in this json. {json_url}
    No incompatible technologies are used together.
    The solution adheres to regulatory and security standards.
    The architecture follows basic compatibility guidelines.
  expected_output: >
    A list of detected violations (if any).
    A confirmation message if no violations are found.
  agent: rule_validation_agent

json_to_eraser_diagram_task:
  description: >
    Your task is to convert the provided architecture JSON present at {diagram_json_url} into
    visually optimal Eraser.io diagram code that precisely follows Eraser.io's syntax requirements.
    CopyThe JSON structure represents a cloud architecture with components, connections, and workflow.

    IMPORTANT REQUIREMENTS:
    - Produce ONLY valid Eraser.io code without any explanations, commentary, or JSON
    - Preserve the exact component structure, naming, and relationships from the JSON input
    - Represent EVERY component and EVERY connection specified in the JSON
    - Organize components using appropriate visual grouping to show logical relationships
    - Maintain clear visualization of data/process flow directions
    - Optimize component spacing and positioning for maximum readability
    - Ensure diagram scales appropriately for both overview and detailed examination

    ICON SELECTION REQUIREMENTS:
    - For each component, select the most appropriate icon from Eraser.io's library based on:
      1. Exact match for the component type/service (first priority)
      2. Parent service provider icon if exact match unavailable (second priority)
      3. Generic category icon that best represents the component's function (third priority)
      4. If no suitable icon exists, use abstract shapes with clear labels
    - For AWS services, use AWS-specific icons when available
    - For Azure services, use Azure-specific icons when available
    - For GCP services, use GCP-specific icons when available
    - For database components, use the specific database type icon (MySQL, PostgreSQL, etc.) when available
    - For generic components like "API" or "Service," use the most semantically appropriate icon

    CONNECTION RENDERING REQUIREMENTS:
    - Represent directional flow using appropriate arrow styling
    - Differentiate connection types (data flow, API calls, dependencies) with appropriate line styles
    - Avoid line crossings whenever possible
    - Use appropriate line routing (orthogonal, curved) based on diagram complexity
    - Add connection labels when specified in the JSON

    LAYOUT OPTIMIZATION REQUIREMENTS:
    - Position components to minimize crossing connections
    - Group related components visually (using containers when appropriate)
    - Arrange components to follow logical left-to-right or top-to-bottom process flow
    - Balance the diagram for visual harmony and equal distribution of elements
    - Ensure components have sufficient spacing to maintain readability

    VALIDATION STEPS:
    Before finalizing, verify that your code:
    1. Represents every component from the JSON
    2. Includes every connection from the JSON
    3. Uses valid Eraser.io syntax for all elements
    4. Maintains proper nesting of components within containers/groups
    5. Uses appropriate icons for all component types
    6. Creates a visually balanced and readable diagram
  expected_output: >
    ONLY valid Eraser.io diagram code that can be directly copied into Eraser.io.
    No explanations, JSON formatting, or anything other than the pure Eraser.io diagram code itself.
  agent: architecture_to_eraser_agent
  output_file: output/finalEraserCode.md